name: Java CI with Maven

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SONARQUBE_HOST: ${{ secrets.SONARQUBE_HOST }}
      SONARQUBE_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_REPO: your-docker-repo/hello-world-war

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run SonarQube analysis
      run: mvn sonar:sonar -Dsonar.projectKey=hello-world-war -Dsonar.host.url=${{ env.SONARQUBE_HOST }} -Dsonar.login=${{ env.SONARQUBE_TOKEN }}

    - name: Log in to Docker Hub
      run: echo ${{ env.DOCKER_PASSWORD }} | docker login -u ${{ env.DOCKER_USERNAME }} --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ env.DOCKER_REPO }}:${{ github.run_id }} .

    - name: Tag Docker image
      run: docker tag ${{ env.DOCKER_REPO }}:${{ github.run_id }} ${{ env.DOCKER_REPO }}:latest

    - name: Push Docker image
      run: |
        docker push ${{ env.DOCKER_REPO }}:${{ github.run_id }}
        docker push ${{ env.DOCKER_REPO }}:latest

    - name: Run Docker container
      run: docker run -d -p 8080:8080 --name hello-world-war ${{ env.DOCKER_REPO }}:${{ github.run_id }}

    - name: Verify Docker container
      run: curl --retry 10 --retry-delay 5 --retry-connrefused http://localhost:8080/hello-world-war
