name: Java CI with Maven

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag yuvalost/hello_world_war1:${{ github.run_number }}

    - name: Log in to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Push the image
      run: docker push yuvalost/hello_world_war1:${{ github.run_number }}

    - name: Tag latest & push
      run: |
        docker tag yuvalost/hello_world_war1:${{ github.run_number }} yuvalost/hello_world_war1:latest
        docker push yuvalost/hello_world_war1:latest

    - name: SonarCloud Analysis
      uses: sonarsource/sonarcloud-github-action@v2
      with:
        args: >
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
          
