name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/hello-world-war:${{ github.run_number }}
      
    - name: Log in to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Push the image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/hello-world-war:${{ github.run_number }}
      
    - name: Tag latest & push
      run: |
            docker tag ${{ secrets.DOCKER_USERNAME }}/hello-world-war:${{ github.run_number }} ${{ secrets.DOCKER_USERNAME }}/hello-world-war:latest
            docker push ${{ secrets.DOCKER_USERNAME }}/hello-world-war:latest
